-- How many orders are there?
SELECT count(DISTINCT"Order ID") AS Total_Orders
 FROM global_superstore;  
-- How many customers have placed at least one order?
SELECT count(DISTINCT"Customer ID") AS Total_Customers
 FROM global_superstore; 
-- What are the total sales generated by the Global Superstore? 
SELECT SUM(Sales) AS Total_Sales
 FROM global_superstore; 
--Which product category generated the highest total sales?
SELECT Category, SUM(Sales) AS Total_Sales
FROM global_superstore
GROUP BY Category
ORDER BY Total_Sales DESC; 
--Which are the top 5 countries by total sales?
SELECT Country, SUM(Sales) AS Total_Sales
FROM global_superstore
GROUP BY Country
ORDER BY Total_Sales DESC
LIMIT 5; 
--Which market generated the highest total profit?
SELECT Market, SUM(Profit) AS Total_Profit
FROM global_superstore
GROUP BY Market
ORDER BY Highest_Profit DESC
LIMIT 1;
